### ISSUE TITLE
Implement the logic for the consequence ratio

### ISSUE THREAD

**Issue by micheles** [gem/oq-risklib#421]
See Anirudh's comment below.

**Comment by raoanirudh** [comment]
Background and full specifications for the extensions to the Scenario Damage calculator to handle multiple loss types and calculate consequences. Specs also hosted at: https://gist.github.com/raoanirudh/a7fd17682fbc3db5538a 

## Introduction

The Scenario Damage Calculator computes damage distribution statistics for all assets in a given exposure model for a single specified earthquake rupture. Damage distribution statistics include the mean and standard deviation of damage fractions for different damage states. This calculator requires the definition of a finite rupture model, an exposure model and a fragility model; the main results are the damage distribution statistics per asset, aggregated damage distribution statistics per taxonomy, aggregated damage distribution statistics for the region, and collapse maps.

Damage distribution statistics can be computed for four different loss types using this calculator: structural damage, nonstructural damage, contents damage, and business interruption.

The rupture characteristics—i.e. the magnitude, hypocenter and fault geometry—are modelled as deterministic in the scenario calculators. Multiple realizations of different possible ground motion fields (GMFs) due to the single rupture are generated, taking into consideration both the inter-event variability of ground motions, and the intra-event residuals obtained from a spatial correlation model for ground motion residuals. The use of logic-trees allows for the consideration of uncertainty in the choice of a GMPE model for the given tectonic region.

As an alternative to computing the GMFs with OpenQuake, users can also provide their own sets of GMFs as input to the Scenario Damage Calculator.

For each GMF realization, damage fractions (the fraction of buildings in each damage state) are estimated for every asset in the exposure model using the provided fragility model, and finally the damage distribution statistics (i.e., the mean damage fractions and standard deviation of damage fractions for all damage states) across all realizations are calculated. The calculator also provides aggregated damage distribution statistics for the portfolio, such as mean damage fractions and standard deviation of damage fractions for each taxonomy in the exposure model, and the mean damage fractions and standard deviation of damage fractions for the total portfolio.

If a consequence model is also provided in addition to the fragility model, the damage state probabilities (i.e. the damage fractions) for each asset are multiplied by the consequence ratios for the corresponding damage states and summed to give the expected consequence ratio for each GM realization. The consequence ratio is multiplied by the respective value of the asset to give the expected consequence. Finally, the mean and standard deviation of the consequence are computed. Similar to the damage distribution, the aggregated consequences per taxonomy and for the total portfolio are also computed.

## Inputs

The basic inputs are the same as those required for the existing scenario damage calculator. The extensions required are listed below:

1. A fragility model file can be specified for the following loss types: structural, nonstructural, contents. The paths for the respective nrml files are provided in the configuration file using the keys: `structural_fragility_file`, `nonstructural_fragility_file`, `contents_fragility_file`, `business_interruption_fragility_file`.

2. A consequence model file can be specified for the following loss types: structural, nonstructural, contents, business interruption, occupants. The paths for the respective nrml files are provided in the configuration file using the keys: `structural_consequence_file`, `nonstructural_consequence_file`, `contents_consequence_file`, `business_interruption_consequence_file`, `occupants_consequence_file`.

    An example consequence model nrml file is provided here: https://github.com/raoanirudh/oq-risk-models/blob/master/beta/inputs/consequence_model.xml, and copied below for convenience:
    
    ```xml
    <?xml version='1.0' encoding='utf-8'?>
    <nrml xmlns="http://openquake.org/xmlns/nrml/0.5">
    
    <consequenceModel id="example" assetCategory="buildings" lossCategory="structural">
    
      <description>consequence model</description>
      <limitStates>ds1 ds2 ds3 ds4</limitStates>
    
      <consequenceFunction id="ATC13_W1" format="PM">
        <lrs>0.00 0.20 0.40 0.60 0.80 1.00</lrs>
        <probabilities ls="ds1">0.600 0.300 0.100 0.000 0.000 0.000</probabilities>
        <probabilities ls="ds2">0.190 0.410 0.320 0.080 0.000 0.000</probabilities>
        <probabilities ls="ds3">0.000 0.090 0.170 0.440 0.240 0.060</probabilities>
        <probabilities ls="ds4">0.000 0.000 0.050 0.150 0.500 0.300</probabilities>
      </consequenceFunction>
    
    
      <consequenceFunction id="W1_Res_LowCode" dist="LN">
        <params ls="ds1" mean="0.05" stddev="0.01"/>
        <params ls="ds2" mean="0.20" stddev="0.05"/>
        <params ls="ds3" mean="0.50" stddev="0.20"/>
        <params ls="ds4" mean="0.80" stddev="0.40"/>
      </consequenceFunction>
    
      <consequenceFunction id="S1_Res_HighCode" dist="BT">
        <params ls="ds1" mean="0.04" stddev="0.01"/>
        <params ls="ds2" mean="0.16" stddev="0.04"/>
        <params ls="ds3" mean="0.32" stddev="0.08"/>
        <params ls="ds4" mean="0.64" stddev="0.16"/>
      </consequenceFunction>
    
    </consequenceModel>
    
    </nrml>
    ```

    Notes about the consequence model schema:
    * the discrete consequence functions will not be implemented; but there is a placeholder in the schema in case we wish to implement this in the future
    * the distributions attribute (‘LN’, ‘BT’) is ignored, only the mean values are extracted; the `stddev` and `dist` are placeholders for future-proofing
    * the lossCategory attributed is ignored and the user will have to provide a different file for each loss type using the keywords structural_consequence_file = ...


## Calculation steps

1. The calculation of the damage fractions proceeds in the same manner as for the existing scenario damage calculator, but with the extension that the damage fractions are now computed for each of the loss types for which fragility models have been provided.

2. The mean consequence ratios for each damage state for each taxonomy are read from the consequence model files for each of the loss types for which consequence models have been provided.

3. The damage state probabilities (i.e. damage fractions) are multiplied by the respective mean consequence ratios and the products are summed to give the expected consequence ratio for each asset for each GM realization. Pseudocode for the calculation procedure is listed below:

	```
	FOR BRANCH IN LOGIC_TREE:
	  FOR GMF IN GMF_SET[BRANCH]:
	    FOR LOSS_TYPE IN LOSS_TYPES:
	      FOR ASSET IN EXPOSURE_MODEL:
	        DAMAGE_FRACTIONS = calculate_damage(FRAGILITY_MODEL[LOSS_TYPE][ASSET.TAXONOMY], GMF)
	        CONSEQUENCE_RATIO = dot_product(DAMAGE_FRACTIONS, CONSEQUENCE_MEANS[LOSS_TYPE][ASSET.TAXONOMY])
	        DAMAGE_DIST[BRANCH][LOSS_TYPE][ASSET.REF][GMF_NUM] = DAMAGE_FRACTIONS * ASSET.NUM[LOSS_TYPE]
	        CONSEQUENCE[BRANCH][LOSS_TYPE][ASSET.REF][GMF_NUM] = CONSEQUENCE_RATIO * ASSET.VAL[LOSS_TYPE]
	  DAMAGE_DIST_PER_TAXONOMY[BRANCH][LOSS_TYPE] = compute_damage_stats(DAMAGE_DIST[BRANCH][LOSS_TYPE])
	  CONSEQUENCE_PER_TAXONOMY[BRANCH][LOSS_TYPE] = compute_consequence_stats(CONSEQUENCE[BRANCH][LOSS_TYPE])
	```

4. The consequence is obtained from the consequence ratio as follows:
  1. For all loss types except occupants, the consequence ratio is multiplied by the respective asset value to give the consequence. This step is identical to the corresponding step in the scenario risk calculator, where the loss ratio is multiplied by the respective asset value to give the loss.
  2. For occupants, the consequence ratio is multiplied by the number of occupants for the respective asset to give the occupants consequence. Again, this step is identical to the corresponding step in the scenario risk calculator, where the loss ratio is multiplied by the respective asset value to give the loss.

5. The mean and standard deviation across all realizations are computed for the consequence for each asset.


## Notes:

1. The structural consequences are computed from the structural damage fractions and the structural consequence model.

2. The nonstructural consequences are computed from the nonstructural damage fractions and the nonstructural consequence model.

3. The contents consequences are computed from the contents damage fractions and the contents consequence model.

4. The business interruption consequences are computed from the business interruption damage fractions and the business interruption consequence model.

5. The occupants consequences are computed from the structural damage fractions and the occupants consequence model.

## Outputs

1. The outputs for the damage distribution are provided in the same manner as done by the existing scenario damage calculator, with separate files for each loss type.

2. The outputs for the consequences follow the same format as the outputs for the scenario risk calculator.
