### ISSUE TITLE
Should IML = 0 be an error?

### ISSUE THREAD

**Issue by micheles** [gem/oq-risklib#584]
This happens when the IMLs are ready from a vulnerability function like this:

```xml
<vulnerabilityModel
    assetCategory="buildings"
    id="Turkey_BalModel_RC_corrected_Turkey_BalModel_corrected"
    lossCategory="structural"
    >
        <vulnerabilityFunction dist="LN" id="URM_1S">
            <imls imt="PGA"> 0.00 0.02 0.041 ... 1.0 </imls>
       ...            
```

The engine works, but a lots of worrisome `divide by zero` RuntimeWarning are printed and the users may get scared. Also, the meaning of a zero level is unclear to me (what's the point of computing the
loss for null hazard?)

**Comment by micheles** [comment]
For the classical damage tests the warning are produced by noDamageLimit = 0 (for discrete functions) and minIML = 0 (for continuous functions). Can we make such cases illegal?

**Comment by raoanirudh** [comment]
Many existing discrete functions, including several in the Global Vulnerability Database, are likely to include the (0, 0) point, since it is useful when plotting the functions. A more graceful way of handling this might be to strip the zero IML points from such functions before running the calculation, thus avoiding the `divide by zero` warnings without throwing errors. Note, however, that in case interpolation is required for such functions (eg. using `steps_per_interval` or `lrem_steps_per_interval`), the zero point should be discarded only after the additional interpolated points have been generated.
