### ISSUE TITLE
Harmonize output names in the datastore

### ISSUE THREAD

**Issue by raoanirudh** [gem/oq-risklib#723]
--
#### Scenario Calculators
**Hazard**
`gmfs` → `ground-motion-fields`
`realizations` → `realizations`

**Damage**
`dmg_by_asset_and_collapse_map` → `damage-asset`
`dmg_by_taxon` → `damage-taxonomy`
`dmg_total` → `damage-aggregate`
`csq_by_asset` → `losses-asset`
`csq_by_taxon` → `losses-taxonomy`
`csq_total` → `losses-aggregate`

**Risk**
`loss_map-rlzs` → `losses-asset`
_(new output)_ → `losses-taxonomy`
`agglosses-rlzs` → `losses-aggregate`

--
#### Classical Calculators
**Hazard**
`hcurves` → `hazard-curves`
`hmaps` → `hazard-maps`
`realizations` → `realizations`
`uhs` → `uniform-hazard-spectra`

**Damage**
`damages-rlzs` → `damage-asset`

**Risk**
{`loss_curves-rlzs`, `loss_curves-stats`} → `loss-curves-asset`
{`loss_maps-rlzs`, `loss_maps-stats`} → `loss-maps`

--
#### Event Based Calculators
**Hazard**
`gmfs` → `ground-motion-fields`
`hcurves` → `hazard-curves`
`hmaps` → `hazard-maps`
`realizations` → `realizations`
`sescollection` → `stochastic-event-sets`
`uhs` → `uniform-hazard-spectra`

**Risk**
`asset_loss_table` → `loss-table-asset`
`agg_loss_table` → `loss-table-aggregate`
{`agg_curve-rlzs`, `agg_curve-stats`} → `loss-curves-aggregate`
{`avg_losses-rlzs`, `avg_losses-stats`} → `average-losses`
{`loss_maps-rlzs`, `loss_maps-stats`} → `loss-maps`
{`rcurves-rlzs`, `loss_curves-stats`} → `loss-curves-asset`

--

**Comment by micheles** [comment]
After much thinking I am not of the idea that we should decouple the datastore, which is for internal usage, from an external hdf5 format. The datastore will change continuously at each release as soon as we find better ways of storing the data; the external format instead will be fixed. 

```
bash
$ oq engine --export <out_id> <out_dir> --exports=hdf5
```

will export the outputs in a stable format. The names should be fixed in the exported files, not in the datastore. I am moving this ticket to release 2.1.
